default_platform(:ios)

platform :ios do
  before_all do
    if is_ci?
      setup_circle_ci
    end
  end

  desc "Build framework and run tests"
  lane :test do
    cocoapods
    scan(
      output_directory: "./output/scan",
      output_types: "junit"
    )
  end

  desc "Build example app"
  lane :build_example do
    filename = "Example-" + ENV["CIRCLE_BRANCH"].to_s + ".ipa"
    cocoapods(podfile: "./Example-sdk/Podfile")
    disable_automatic_code_signing(
      path: "./Example-sdk/Example-sdk.xcodeproj",
      code_sign_identity: "iPhone Distribution"
    )
    match(type: "adhoc", readonly: is_ci)
    update_project_team(path: "./Example-sdk/Example-sdk.xcodeproj")
    update_project_provisioning(
      profile: ENV["sigh_com.payoneer.mrs.examplesdk_adhoc_profile-path"],
      xcodeproj: "./Example-sdk/Example-sdk.xcodeproj"
    )
    build_ios_app(
      scheme: "Example",
      configuration: "Release",
      workspace: "./Example-sdk/Example-sdk.xcworkspace",
      export_method: "ad-hoc",
      output_directory: "/tmp/workspace/output",
      output_name: filename,
      derived_data_path: "/tmp/workspace/derived_data"
    )
  end

  desc "Upload binary to Browserstack"
  lane :browserstack do
    path = "/tmp/workspace/output/Example-" + ENV["CIRCLE_BRANCH"].to_s + ".ipa"
    upload_to_browserstack_app_live(
      browserstack_username: ENV["BROWSERSTACK_USERNAME"],
      browserstack_access_key: ENV["BROWSERSTACK_ACCESS_KEY"],
      file_path: path
    )
  end

  desc "Run UI tests"
  lane :ui_test do
    cocoapods(podfile: "./Example-sdk/Podfile")
    run_tests(
      scheme: "Example",
      derived_data_path: "/tmp/workspace/derived_data",
      workspace: "Example-sdk/Example-sdk.xcworkspace",
      devices: ["iPhone 12"],
      output_directory: "./output/scan",
      output_types: "junit",
      result_bundle: true,
      xcargs: "MERCHANT_CODE=" + ENV["MERCHANT_CODE"] + " MERCHANT_PAYMENT_TOKEN=" + ENV["MERCHANT_PAYMENT_TOKEN"]
    )
  end

end