name: Public deployment

on:
  push:
    branches:
      - master

concurrency: 
  group: public-deployment-${{ github.head_ref }}
  cancel-in-progress: false

jobs:
  deploy-to-cocoapods:
    name: CocoaPods
    runs-on: macos-latest
    environment: CocoaPods

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies specified in Gemfile
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true

      - name: Publish to CocoaPods
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: bundle exec fastlane deploy
