name: Manual tests

on:
  push:
    branches:
      - PCX-2120-github-actions
  workflow_dispatch:
  pull_request:
    branches:
      - develop

concurrency: 
  group: tests-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    env:
      example_app_binary: Binary/ExampleCheckout-${{ github.base_ref }}.ipa

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install the dependencies specified in Gemfile
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true

      - name: Cache pods
        id: cache-pods
        uses: actions/cache@v2
        env:
          cache-name: example-app-pods
        with:
          path: ExampleCheckout/Pods/
          key: cache-${{ env.cache-name }}-${{ hashFiles('ExampleCheckout/Podfile.lock') }}

      - name: Build example application
        run: bundle exec fastlane build_example_swift binary:${{ env.example_app_binary }}

      - name: Upload to BrowserStack
        env: 
          username: ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        run: bundle exec fastlane browserstack binary:${{ env.example_app_binary }}