name: Publish to Browserstack

on:
  workflow_dispatch:
  push:
    branches:
      - PCX-2120-github-actions

concurrency: 
  group: browserstack-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  upload-to-browserstack:
    runs-on: macos-latest
    environment: Browserstack

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get branch name (merge)
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Install the dependencies specified in Gemfile
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true

      - name: Cache pods
        id: cache-pods
        uses: actions/cache@v2
        env:
          cache-name: example-app-pods
        with:
          path: ExampleCheckout/Pods/
          key: cache-${{ env.cache-name }}-${{ hashFiles('ExampleCheckout/Podfile.lock') }}

      - name: Install Pods
        if: steps.cache-pods.outputs.cache-hit != 'true'
        env:
          project-directory: ExampleCheckout/
        run: bundle exec pod install --deployment --project-directory=${{ env.project-directory }}

      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode --output $PP_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Build example application
        env:
          ipa-binary: ExampleCheckout-${{ env.BRANCH_NAME }}.ipa
        run: bundle exec fastlane build_example_swift binary:${{ env.ipa-binary }}

      - name: Clean up keychain and provisioning profile
        if: ${{ always() }}
        run: |
          security delete-keychain $RUNNER_TEMP/app-signing.keychain-db
          rm ~/Library/MobileDevice/Provisioning\ Profiles/build_pp.mobileprovision

      - name: Upload to BrowserStack
        env: 
          BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
          BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}
          ipa-binary: ExampleCheckout-${{ env.BRANCH_NAME }}.ipa
        run: bundle exec fastlane browserstack binary:${{ env.ipa-binary }}